cluster:
  num_nodes: 1
  component_placement:
    model: 0-1

client:
  group_name: "mcp_python_sandbox_client_group"
  placement_strategy:
    type: "node"
    node_id: 0

mcp:
  default_timeout: 30
  max_history_size: 100

runner:
  task_type: mcp_python_sandbox
  experiment_name: test-mcp-python-sandbox
  logger:
    log_path: ${runner.output_dir}/${runner.experiment_name}
    project_name: test-mcp-python-sandbox
    experiment_name: ${runner.experiment_name}
    log_level: INFO
  output_dir: ../results
