defaults:
  - base_calc_x

runner:
  logger:
    project_name: rlinf-calc-x-qwen2.5-1.5b-routerserver-multiturn
  experiment_name: calc-x-agl-qwen2.5-1.5b-routerserver-multiturn

algorithm:
  advantage_mode: turn

actor:
  pack_traj: False

rollout:
  sglang:
    serving_mode: router_server
    router:
      host: 0.0.0.0
      port: 30000
      policy: round_robin
