defaults:
  - base_calc_x

runner:
  logger:
    project_name: rlinf-calc-x-qwen2.5-1.5b-enginehttp-turn
  experiment_name: calc-x-agl-qwen2.5-1.5b-enginehttp-turn

algorithm:
  advantage_mode: turn

actor:
  pack_traj: False

rollout:
  sglang:
    serving_mode: worker_http
